spring.application.name=subsidy-tracker

# H2 Database configuration (Active by default)
# spring.datasource.url=jdbc:h2:mem:subsidydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ----------------- MYSQL DATABASE CONFIGURATION -----------------
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://127.0.0.1:3306/subsidydb}
spring.datasource.driverClassName=${SPRING_DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:"Your_Password"}
spring.jpa.database-platform=${SPRING_JPA_DIALECT:org.hibernate.dialect.MySQLDialect}
# ----------------------------------------------------------------

# JPA/Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.hbm2ddl.auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server configuration
server.port=8081

# Module 2 - Eligibility Scoring & Verification Workflow
workflow.fast-track.grant-threshold=50000

